// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxhpkm04maXTpSftKvzIr4d-p-QwQXdA',
    appId: '1:1086639829001:android:406b7b3b361004ff0b88d8',
    messagingSenderId: '1086639829001',
    projectId: 'cardpocket-3650f',
    storageBucket: 'cardpocket-3650f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1tHIrExfTFnuVwk5tYOAjGsaQnJ8vsWI',
    appId: '1:1086639829001:ios:e40c5623d68253430b88d8',
    messagingSenderId: '1086639829001',
    projectId: 'cardpocket-3650f',
    storageBucket: 'cardpocket-3650f.appspot.com',
    iosClientId: '1086639829001-j44s5eal413d3rmk0ps2jn4hueledplm.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVgWliQKQ9zXLPUcgh8lOZVHjmWDAnOiI',
    appId: '1:1086639829001:web:06cf6b701fdcdffd0b88d8',
    messagingSenderId: '1086639829001',
    projectId: 'cardpocket-3650f',
    authDomain: 'cardpocket-3650f.firebaseapp.com',
    storageBucket: 'cardpocket-3650f.appspot.com',
  );

}